import { Question } from '../types';

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: 'q-1',
    number: 1,
    question: 'Planet apakah yang terdekat dari Matahari di tata surya kita?',
    category: 'Astronomi',
    type: 'multiple_choice',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 30,
    options: ['Venus', 'Merkurius', 'Mars', 'Bumi'],
    correctAnswer: 'Merkurius',
    explanation: 'Merkurius adalah planet terdekat dari Matahari dengan jarak rata-rata sekitar 57,9 juta km.',
  },
  {
    id: 'q-2',
    number: 2,
    question: 'Gas apakah yang diserap oleh tumbuhan hijau pada proses fotosintesis?',
    category: 'Biologi',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 30,
    acceptedAnswers: ['karbon dioksida', 'karbondioksida', 'co2'],
    correctAnswer: 'Karbon Dioksida (CO2)',
    explanation: 'Tumbuhan menyerap karbon dioksida (CO2) dan air untuk menghasilkan glukosa dan oksigen dengan bantuan cahaya matahari.',
  },
  {
    id: 'q-3',
    number: 3,
    question: 'Jodohkan nama negara berikut dengan ibukota resminya:',
    category: 'Geografi',
    type: 'matching',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 45,
    pairs: [
      { left: 'Jepang', right: 'Tokyo' },
      { left: 'Perancis', right: 'Paris' },
      { left: 'Australia', right: 'Canberra' },
      { left: 'Mesir', right: 'Kairo' },
    ],
    explanation: 'Ibukota Jepang adalah Tokyo, Perancis adalah Paris, Australia adalah Canberra, dan Mesir adalah Kairo.',
  },
  {
    id: 'q-4',
    number: 4,
    question: 'Berapakah hasil dari operasi perhitungan matematika: 15 + (4 x 6) - 10?',
    category: 'Matematika',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 30,
    acceptedAnswers: ['29'],
    correctAnswer: '29',
    explanation: 'Dahulukan perkalian: 4 x 6 = 24. Kemudian 15 + 24 - 10 = 29.',
  },
  {
    id: 'q-5',
    number: 5,
    question: 'Organel sel yang sering dijuluki sebagai "The Powerhouse of Cell" (pembangkit tenaga sel) adalah:',
    category: 'Biologi',
    type: 'multiple_choice',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 30,
    options: ['Ribosom', 'Mitokondria', 'Nukleus', 'Badan Golgi'],
    correctAnswer: 'Mitokondria',
    explanation: 'Mitokondria menghasilkan sebagian besar pasokan ATP (energi kimiawi seluler).',
  },
  {
    id: 'q-6',
    number: 6,
    question: 'Benar atau Salah: Cahaya merambat lebih cepat di dalam ruang hampa udara daripada di dalam air.',
    category: 'Fisika',
    type: 'true_false',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 20,
    options: ['Benar', 'Salah'],
    correctAnswer: 'Benar',
    explanation: 'Kecepatan cahaya di ruang hampa adalah ~300.000 km/s, sedangkan di dalam air melambat menjadi ~225.000 km/s.',
  },
  {
    id: 'q-7',
    number: 7,
    question: 'Jodohkan lambang unsur kimia berikut dengan nama unsurnya:',
    category: 'Kimia',
    type: 'matching',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 45,
    pairs: [
      { left: 'Au', right: 'Emas (Gold)' },
      { left: 'Ag', right: 'Perak (Silver)' },
      { left: 'Fe', right: 'Besi (Iron)' },
      { left: 'Cu', right: 'Tembaga (Copper)' },
    ],
    explanation: 'Au = Aurum (Emas), Ag = Argentum (Perak), Fe = Ferrum (Besi), Cu = Cuprum (Tembaga).',
  },
  {
    id: 'q-8',
    number: 8,
    question: 'Siapakah ilmuwan penemu hukum gravitasi universal yang terkenal dengan kisah apel jatuh?',
    category: 'Fisika',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 30,
    acceptedAnswers: ['isaac newton', 'newton', 'sir isaac newton'],
    correctAnswer: 'Sir Isaac Newton',
    explanation: 'Sir Isaac Newton merumuskan hukum gravitasi dan hukum gerak dalam karyanya Principia Mathematica.',
  },
  {
    id: 'q-9',
    number: 9,
    question: 'Berapa jumlah sudut dalam total pada sebuah segitiga sembarang?',
    category: 'Matematika',
    type: 'multiple_choice',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 25,
    options: ['90 derajat', '180 derajat', '270 derajat', '360 derajat'],
    correctAnswer: '180 derajat',
    explanation: 'Jumlah ketiga sudut dalam pada setiap bidang segitiga Euclidean selalu tepat 180 derajat.',
  },
  {
    id: 'q-10',
    number: 10,
    question: 'Apakah nama samudera terluas dan terdalam di permukaan bumi?',
    category: 'Geografi',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 25,
    acceptedAnswers: ['pasifik', 'samudra pasifik', 'samudera pasifik', 'pacific'],
    correctAnswer: 'Samudera Pasifik',
    explanation: 'Samudera Pasifik mencakup lebih dari 30% luas permukaan Bumi dan memiliki Palung Mariana sebagai titik terdalam.',
  },
  {
    id: 'q-11',
    number: 11,
    question: 'Jodohkan tokoh pahlawan nasional dengan julukan daerah asalnya:',
    category: 'Sejarah',
    type: 'matching',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 45,
    pairs: [
      { left: 'Sultan Hasanuddin', right: 'Ayam Jantan dari Timur' },
      { left: 'Pangeran Diponegoro', right: 'Perang Jawa' },
      { left: 'Tuanku Imam Bonjol', right: 'Perang Padri' },
      { left: 'Pattimura', right: 'Pahlawan Maluku' },
    ],
    explanation: 'Julukan pahlawan mencerminkan perjuangan gigih mereka melawan penjajahan.',
  },
  {
    id: 'q-12',
    number: 12,
    question: 'Organ tubuh manusia yang berfungsi memompa darah ke seluruh tubuh adalah:',
    category: 'Biologi',
    type: 'multiple_choice',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 20,
    options: ['Paru-paru', 'Hati', 'Jantung', 'Ginjal'],
    correctAnswer: 'Jantung',
    explanation: 'Jantung berdenyut rata-rata 60-100 kali per menit untuk mengalirkan oksigen dan nutrisi.',
  },
  {
    id: 'q-13',
    number: 13,
    question: 'Apakah nama satuan standar internasional (SI) untuk mengukur gaya?',
    category: 'Fisika',
    type: 'short_answer',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 30,
    acceptedAnswers: ['newton', 'n'],
    correctAnswer: 'Newton (N)',
    explanation: 'Satuan gaya adalah Newton (N), dinamai untuk menghormati Sir Isaac Newton. 1 N = 1 kg·m/s².',
  },
  {
    id: 'q-14',
    number: 14,
    question: 'Jika 3x + 9 = 24, maka berapakah nilai dari x?',
    category: 'Matematika',
    type: 'short_answer',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 30,
    acceptedAnswers: ['5'],
    correctAnswer: '5',
    explanation: '3x = 24 - 9 = 15 => x = 15 / 3 = 5.',
  },
  {
    id: 'q-15',
    number: 15,
    question: 'Jodohkan besaran fisika berikut dengan satuannya dalam Sistem Internasional (SI):',
    category: 'Fisika',
    type: 'matching',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 45,
    pairs: [
      { left: 'Arus Listrik', right: 'Ampere' },
      { left: 'Hambatan Listrik', right: 'Ohm' },
      { left: 'Energi / Usaha', right: 'Joule' },
      { left: 'Daya', right: 'Watt' },
    ],
    explanation: 'Arus = Ampere, Hambatan = Ohm, Energi = Joule, Daya = Watt.',
  },
  {
    id: 'q-16',
    number: 16,
    question: 'Benar atau Salah: Logam merkuri (raksa) adalah satu-satunya logam yang berwujud cair pada suhu kamar normal.',
    category: 'Kimia',
    type: 'true_false',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 20,
    options: ['Benar', 'Salah'],
    correctAnswer: 'Benar',
    explanation: 'Merkuri (Hg) memiliki titik leleh -38,83 °C sehingga berwujud cair pada suhu ruang 25 °C.',
  },
  {
    id: 'q-17',
    number: 17,
    question: 'Berapakah kecepatan sudut jarum jam pendek (jam) dalam bergerak per jam?',
    category: 'Matematika',
    type: 'multiple_choice',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 35,
    options: ['15 derajat', '30 derajat', '45 derajat', '60 derajat'],
    correctAnswer: '30 derajat',
    explanation: 'Satu putaran penuh jam adalah 360 derajat dibagi 12 jam = 30 derajat per jam.',
  },
  {
    id: 'q-18',
    number: 18,
    question: 'Apakah nama proses perubahan wujud benda dari padat langsung menjadi gas tanpa mencair terlebih dahulu?',
    category: 'Kimia',
    type: 'short_answer',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 30,
    acceptedAnswers: ['menyublim', 'sublimasi'],
    correctAnswer: 'Menyublim (Sublimasi)',
    explanation: 'Contoh sublimasi adalah kapur barus (kamper) dan es kering (dry ice) yang langsung menjadi gas.',
  },
  {
    id: 'q-19',
    number: 19,
    question: 'Jodohkan penemuan teknologi berikut dengan tokoh penemunya:',
    category: 'Teknologi',
    type: 'matching',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 50,
    pairs: [
      { left: 'Telepon', right: 'Alexander Graham Bell' },
      { left: 'Bola Lampu Pijar', right: 'Thomas Alva Edison' },
      { left: 'Pesawat Terbang', right: 'Wright Bersaudara' },
      { left: 'Radio', right: 'Guglielmo Marconi' },
    ],
    explanation: 'Para ilmuwan dan penemu pionir teknologi dunia modern.',
  },
  {
    id: 'q-20',
    number: 20,
    question: 'Di manakah candi Buddha terbesar di dunia yang merupakan warisan UNESCO berada?',
    category: 'Sejarah',
    type: 'multiple_choice',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 25,
    options: ['Candi Prambanan', 'Candi Borobudur', 'Candi Mendut', 'Candi Penataran'],
    correctAnswer: 'Candi Borobudur',
    explanation: 'Candi Borobudur di Magelang, Jawa Tengah didirikan pada wangsa Syailendra abad ke-8 masehi.',
  },
  {
    id: 'q-21',
    number: 21,
    question: 'Apakah rumus kimia dari gas ozon yang melindungi bumi dari radiasi ultraviolet berbahaya?',
    category: 'Kimia',
    type: 'short_answer',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 25,
    acceptedAnswers: ['o3'],
    correctAnswer: 'O3',
    explanation: 'Ozon tersusun atas tiga atom oksigen (O3) di lapisan stratosfer.',
  },
  {
    id: 'q-22',
    number: 22,
    question: 'Benar atau Salah: Benua Antartika adalah gurun terluas di dunia.',
    category: 'Geografi',
    type: 'true_false',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 25,
    options: ['Benar', 'Salah'],
    correctAnswer: 'Benar',
    explanation: 'Gurun didefinisikan berdasarkan curah hujan sangat rendah (<250 mm/tahun). Antartika adalah gurun kutub terluas di dunia.',
  },
  {
    id: 'q-23',
    number: 23,
    question: 'Berapakah akar kuadrat dari 625?',
    category: 'Matematika',
    type: 'short_answer',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 25,
    acceptedAnswers: ['25'],
    correctAnswer: '25',
    explanation: '25 x 25 = 625.',
  },
  {
    id: 'q-24',
    number: 24,
    question: 'Jodohkan istilah geografi berikut dengan maknanya:',
    category: 'Geografi',
    type: 'matching',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 45,
    pairs: [
      { left: 'Episentrum', right: 'Titik pusat gempa di permukaan bumi' },
      { left: 'Hiposentrum', right: 'Titik pusat gempa di dalam perut bumi' },
      { left: 'Tsunami', right: 'Gelombang laut akibat gempa bawah laut' },
      { left: 'Kawah', right: 'Mulut lubang keluarnya magma gunung berapi' },
    ],
    explanation: 'Istilah-istilah penting dalam seismologi dan vulkanologi geografi.',
  },
  {
    id: 'q-25',
    number: 25,
    question: 'Lapisan atmosfer bumi tempat terjadinya fenomena cuaca (awan, hujan, badai) adalah:',
    category: 'Sains',
    type: 'multiple_choice',
    difficulty: 'Sedang',
    points: 200,
    timeLimit: 30,
    options: ['Troposfer', 'Stratosfer', 'Mesosfer', 'Termosfer'],
    correctAnswer: 'Troposfer',
    explanation: 'Troposfer adalah lapisan atmosfer terbawah (0-12 km) yang menampung 80% massa udara dan fenomena cuaca.',
  },
  {
    id: 'q-26',
    number: 26,
    question: 'Siapakah presiden pertama Republik Indonesia yang memproklamasikan kemerdekaan pada 17 Agustus 1945?',
    category: 'Sejarah',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 25,
    acceptedAnswers: ['soekarno', 'sukarno', 'ir soekarno', 'ir. soekarno'],
    correctAnswer: 'Ir. Soekarno',
    explanation: 'Bung Karno bersama Bung Hatta memproklamasikan kemerdekaan Indonesia di Pegangsaan Timur 56.',
  },
  {
    id: 'q-27',
    number: 27,
    question: 'Hewan yang mengalami metamorfosis sempurna melewati 4 tahapan: telur -> larva -> pupa -> imago. Manakah di bawah ini yang bermetamorfosis sempurna?',
    category: 'Biologi',
    type: 'multiple_choice',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 25,
    options: ['Kupu-kupu', 'Belalang', 'Kecoa', 'Capung'],
    correctAnswer: 'Kupu-kupu',
    explanation: 'Kupu-kupu mengalami metamorfosis sempurna (ulat -> kepompong -> kupu-kupu). Belalang dan kecoa bermetamorfosis tidak sempurna.',
  },
  {
    id: 'q-28',
    number: 28,
    question: 'Jodohkan rumus bangun datar berikut dengan namanya:',
    category: 'Matematika',
    type: 'matching',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 50,
    pairs: [
      { left: '1/2 x alas x tinggi', right: 'Luas Segitiga' },
      { left: 'π x r²', right: 'Luas Lingkaran' },
      { left: 'panjang x lebar', right: 'Luas Persegi Panjang' },
      { left: 'sisi x sisi', right: 'Luas Persegi' },
    ],
    explanation: 'Rumus baku perhitungan luas bangun geometri datar dalam matematika.',
  },
  {
    id: 'q-29',
    number: 29,
    question: 'Berapakah jumlah hari dalam satu tahun kabisat?',
    category: 'Astronomi',
    type: 'short_answer',
    difficulty: 'Mudah',
    points: 100,
    timeLimit: 20,
    acceptedAnswers: ['366', '366 hari'],
    correctAnswer: '366 Hari',
    explanation: 'Tahun kabisat memiliki tambahan satu hari pada bulan Februari (29 hari), sehingga totalnya 366 hari.',
  },
  {
    id: 'q-30',
    number: 30,
    question: 'Pertanyaan Puncak Grand Final COC: Berapakah nilai dari 2 pangkat 10 (2¹⁰)?',
    category: 'Matematika',
    type: 'short_answer',
    difficulty: 'Sukar',
    points: 300,
    timeLimit: 30,
    acceptedAnswers: ['1024'],
    correctAnswer: '1024',
    explanation: '2¹⁰ = 1024, angka yang sangat fundamental dalam komputasi digital (1 Kilobyte = 1024 bytes).',
  },
];

export const INITIAL_TEAMS = [
  {
    id: 'team-1',
    number: 1,
    name: 'Tim Garuda',
    color: '#EF4444',
    badgeBg: 'bg-red-500/20 text-red-300 border-red-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🦅',
  },
  {
    id: 'team-2',
    number: 2,
    name: 'Tim Phoenix',
    color: '#F59E0B',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🔥',
  },
  {
    id: 'team-3',
    number: 3,
    name: 'Tim Dragon',
    color: '#10B981',
    badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🐉',
  },
  {
    id: 'team-4',
    number: 4,
    name: 'Tim Titan',
    color: '#06B6D4',
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '⚡',
  },
  {
    id: 'team-5',
    number: 5,
    name: 'Tim Valkyrie',
    color: '#8B5CF6',
    badgeBg: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '⚔️',
  },
  {
    id: 'team-6',
    number: 6,
    name: 'Tim Orion',
    color: '#EC4899',
    badgeBg: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🌟',
  },
  {
    id: 'team-7',
    number: 7,
    name: 'Tim Griffin',
    color: '#3B82F6',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🛡️',
  },
  {
    id: 'team-8',
    number: 8,
    name: 'Tim Kraken',
    color: '#14B8A6',
    badgeBg: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🌊',
  },
  {
    id: 'team-9',
    number: 9,
    name: 'Tim Chimera',
    color: '#F97316',
    badgeBg: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '🦁',
  },
  {
    id: 'team-10',
    number: 10,
    name: 'Tim Aegis',
    color: '#6366F1',
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    score: 0,
    correctCount: 0,
    wrongCount: 0,
    avatar: '👑',
  },
];
